CREATE TABLE IF NOT EXISTS calculations (
    id SERIAL PRIMARY KEY,
    "businessId" INTEGER NOT NULL REFERENCES businesses(id),
    "totalIncome" NUMERIC NOT NULL DEFAULT 0,
    "incomeTax" NUMERIC NOT NULL DEFAULT 0,
    "totalExpense" NUMERIC NOT NULL DEFAULT 0,
    "totalFixedCosts" NUMERIC NOT NULL DEFAULT 0,
    salary NUMERIC NOT NULL DEFAULT 0,
    "salaryTax" NUMERIC NOT NULL DEFAULT 0,
    profit NUMERIC NOT NULL DEFAULT 0,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    "totalSale" NUMERIC NOT NULL DEFAULT 0,
    "addedMoney" NUMERIC NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
