CREATE TABLE IF NOT EXISTS total_expenses (
    id SERIAL PRIMARY KEY,
    "businessId" INTEGER NOT NULL REFERENCES businesses(id),
    total NUMERIC NOT NULL DEFAULT 0,
    cash NUMERIC NOT NULL DEFAULT 0,
    card NUMERIC NOT NULL DEFAULT 0,
    description TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
