CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    "firstName" CHARACTER VARYING(30) NOT NULL,
    "lastName" CHARACTER VARYING(50) NOT NULL,
    "phoneNumber" TEXT,
    "userName" CHARACTER VARYING(30) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role INTEGER NOT NULL DEFAULT 0,
    "inviterCode" TEXT,
    "offerCode" TEXT,
    "isVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    "isExpired" BOOLEAN NOT NULL DEFAULT FALSE,
    "telegramUserId" BIGINT NOT NULL DEFAULT 0,
    "expirationDate" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
