CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    "businessId" INTEGER NOT NULL REFERENCES businesses(id),
    name TEXT NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
