ALTER TABLE users DROP COLUMN IF EXISTS "telegramUserId";
ALTER TABLE users DROP COLUMN IF EXISTS "expirationDate";
ALTER TABLE users DROP COLUMN IF EXISTS "inviterCode";
ALTER TABLE users DROP COLUMN IF EXISTS "offerCode";
ALTER TABLE users DROP COLUMN IF EXISTS "isVerified";
ALTER TABLE users DROP COLUMN IF EXISTS "isExpired";
