CREATE TABLE IF NOT EXISTS businesses (
    id SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL REFERENCES users(id),
    name CHARACTER VARYING(100),
    description CHARACTER VARYING(500),
    "businessAccountNumber" CHARACTER VARYING(20),
    balance NUMERIC NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "address" CHARACTER VARYING(255)
);
