package main

import (
	"fmt"
	"io/ioutil"
	"strings"
)

func main() {
	jsonBytes, err := ioutil.ReadFile("docs/swagger.json")
	if err != nil {
		panic(err)
	}
	jsonStr := string(jsonBytes)
	
	// Escape backticks for Go string literal
	jsonStr = strings.ReplaceAll(jsonStr, "`", "` + \"`\" + `")

	content := fmt.Sprintf(`// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = ` + "`" + `%s` + "`" + `

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "SavdoSklad API",
	Description:      "SavdoSklad biznes boshqaruv tizimi API hujjatlari",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
`, jsonStr)

	err = ioutil.WriteFile("docs/docs.go", []byte(content), 0644)
	if err != nil {
		panic(err)
	}
	fmt.Println("Successfully restored docs/docs.go")
}
