CREATE TABLE IF NOT EXISTS fixed_costs (
    id SERIAL PRIMARY KEY,
    name CHARACTER VARYING(50),
    description CHARACTER VARYING(150),
    amount NUMERIC NOT NULL DEFAULT 0,
    type INTEGER NOT NULL DEFAULT 0,
    "businessId" INTEGER NOT NULL REFERENCES businesses(id),
    "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
