CREATE TABLE IF NOT EXISTS total_refunds (
    id SERIAL PRIMARY KEY,
    description TEXT,
    total NUMERIC NOT NULL DEFAULT 0,
    cash NUMERIC NOT NULL DEFAULT 0,
    card NUMERIC NOT NULL DEFAULT 0,
    click NUMERIC NOT NULL DEFAULT 0,
    debt NUMERIC NOT NULL DEFAULT 0,
    "clientNumber" TEXT,
    "debtLimitDate" TIMESTAMP WITH TIME ZONE,
    "businessId" INTEGER NOT NULL REFERENCES businesses(id),
    "clientId" INTEGER,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
