CREATE TABLE IF NOT EXISTS money (
    id SERIAL PRIMARY KEY,
    value NUMERIC NOT NULL DEFAULT 0,
    description CHARACTER VARYING(200),
    "amountType" INTEGER NOT NULL DEFAULT 0,
    "businessId" INTEGER NOT NULL REFERENCES businesses(id),
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
