ALTER TABLE users ADD COLUMN IF NOT EXISTS image TEXT DEFAULT '';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS image TEXT DEFAULT '';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS image TEXT DEFAULT '';
