ALTER TABLE user_businesses ADD COLUMN can_add BOOLEAN DEFAULT FALSE;
ALTER TABLE user_businesses ADD COLUMN can_edit BOOLEAN DEFAULT FALSE;
ALTER TABLE user_businesses ADD COLUMN can_delete BOOLEAN DEFAULT FALSE;
